apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: g8t7tqadn-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:8191a29b0ba79cd3c9199bdce141537af8f3e6bd@sha256:5c6536afcf08e787ca55831d8188ba7aba098a722ff72c100934fc52d4d5e3f0
          name: container-image
