apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: g8t7tqadn-nodejs
  janus-idp.io/tekton: g8t7tqadn-nodejs
  backstage.io/kubernetes-id: g8t7tqadn-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: g8t7tqadn-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
